// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kigmpvibvsbzsjwdtuiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZ21wdmlidnNienNqd2R0dWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyODMyODYsImV4cCI6MjA1MTg1OTI4Nn0.oJhKtsJd8uWbe6ZGmPDhnLkG9ybm-4HikOPwdGkqln0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);